[package]
name = "quick-stack"
version = "0.2.0"
edition = "2021"

[dependencies]
better-panic = "0.3.0"
clap = { version = "4.5.4", features = ["cargo"] }
colored = "2.1.0"
regex = "1.10.4"
thiserror = "1.0.61"
xdg = "2.5.2"

[profile.release]
lto = true
codegen-units = 1
strip = "symbols"
